/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import banquise from 'url:./banquise-min.glb'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(banquise)
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry}  scale={7} position={[0,0,0]}>

				<meshStandardMaterial color="#777" wireframe={true}></meshStandardMaterial>
			</mesh>
    </group>
  )
}

useGLTF.preload(banquise)
